{
  "a1.medium": {"up": "a1.large", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "a1.large": {"up": "a1.xlarge", "down": "a1.medium", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "a1.xlarge": {"up": "a1.2xlarge", "down": "a1.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "a1.2xlarge": {"up": "a1.4xlarge", "down": "a1.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "a1.4xlarge": {"up": null, "down": "a1.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "a1.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c1.medium": {"up": "c1.xlarge", "down": null, "superseded":  {"regular": "c5.large","next_gen": "", "burstable": "", "amd": ""}, "ec2_classic": true, "enhanced_networking": false},
  "c1.xlarge":  {"up": null, "down": "c1.medium", "superseded":  {"regular": "c5.xlarge","next_gen": "", "burstable": "", "amd": ""}, "ec2_classic": true, "enhanced_networking": false},
  "c3.large": {"up": "c3.xlarge", "down": null, "superseded":  {"regular": "c5.large","next_gen": "", "burstable": "", "amd": ""}, "ec2_classic": true, "enhanced_networking": true},
  "c3.xlarge": {"up": "c3.2xlarge", "down": "c3.large", "superseded":  {"regular": "c5.xlarge","next_gen": "", "burstable": "", "amd": ""}, "ec2_classic": true, "enhanced_networking": true},
  "c3.2xlarge": {"up": "c3.4xlarge", "down": "c3.xlarge", "superseded":  {"regular": "c3.2xlarge","next_gen": "", "burstable": "", "amd": ""}, "ec2_classic": true, "enhanced_networking": true},
  "c3.4xlarge": {"up": "c3.8xlarge", "down": "c3.2xlarge", "superseded":  {"regular": "c3.4xlarge","next_gen": "", "burstable": "", "amd": ""}, "ec2_classic": true, "enhanced_networking": true},
  "c3.8xlarge": {"up": null, "down": "c3.4xlarge", "superseded":  {"regular": "c5.9xlarge","next_gen": "", "burstable": "", "amd": ""}, "ec2_classic": true, "enhanced_networking": true},
  "c4.large": {"up": "c4.xlarge", "down": null, "superseded":  {"regular": "c5.large","next_gen": "", "burstable": "", "amd": ""}, "ec2_classic": false, "enhanced_networking": true},
  "c4.xlarge": {"up": "c4.2xlarge", "down": "c4.large", "superseded":  {"regular": "c5.xlarge","next_gen": "", "burstable": "", "amd": ""}, "ec2_classic": false, "enhanced_networking": true},
  "c4.2xlarge": {"up": "c4.4xlarge", "down": "c4.xlarge", "superseded":  {"regular": "c5.2xlarge","next_gen": "", "burstable": "", "amd": ""}, "ec2_classic": false, "enhanced_networking": true},
  "c4.4xlarge": {"up": "c4.8xlarge", "down": "c4.2xlarge", "superseded":  {"regular": "c5.4xlarge","next_gen": "", "burstable": "", "amd": ""}, "ec2_classic": false, "enhanced_networking": true},
  "c4.8xlarge": {"up": null, "down": "c4.4xlarge", "superseded": {"regular": "c5.9xlarge","next_gen": "", "burstable": "", "amd": ""}, "ec2_classic": false, "enhanced_networking": true},
  "c5.large": {"up": "c5.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5.xlarge": {"up": "c5.2xlarge", "down": "c5.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5.2xlarge": {"up": "c5.4xlarge", "down": "c5.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5.4xlarge": {"up": "c5.9xlarge", "down": "c5.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5.9xlarge": {"up": "c5.12xlarge", "down": "c5.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5.12xlarge": {"up": "c5.18xlarge", "down": "c5.9xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5.18xlarge": {"up": "c5.24xlarge", "down": "c5.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5.24xlarge": {"up": null, "down": "c18.18xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5a.large": {"up": "c5a.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5a.xlarge": {"up": "c5a.2xlarge", "down": "c5a.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5a.2xlarge": {"up": "c5a.4xlarge", "down": "c5a.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5a.4xlarge": {"up": "c5a.8xlarge", "down": "c5a.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5a.8xlarge": {"up": "c5a.12xlarge", "down": "c5a.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5a.12xlarge": {"up": "c5a.16xlarge", "down": "c5a.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5a.16xlarge": {"up": "c5a.24xlarge", "down": "c5a.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5a.24xlarge": {"up": null, "down": "c18.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5d.large": {"up": "c5d.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5d.xlarge": {"up": "c5d.2xlarge", "down": "c5d.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5d.2xlarge": {"up": "c5d.4xlarge", "down": "c5d.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5d.4xlarge": {"up": "c5d.9xlarge", "down": "c5d.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5d.9xlarge": {"up": "c5d.12xlarge", "down": "c5d.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5d.12xlarge": {"up": "c5d.18xlarge", "down": "c5d.9xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5d.18xlarge": {"up": "c5d.24xlarge", "down": "c5d.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5d.24xlarge": {"up": null, "down": "c5d.18xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5d.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5n.large": {"up": "c5n.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5n.xlarge": {"up": "c5n.2xlarge", "down": "c5n.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5n.2xlarge": {"up": "c5n.4xlarge", "down": "c5n.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5n.4xlarge": {"up": "c5n.9xlarge", "down": "c5n.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5n.9xlarge": {"up": "c5n.18xlarge", "down": "c5n.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5n.18xlarge": {"up": null, "down": "c5n.9xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c5n.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6g.medium": {"up": "c6g.large", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6g.large": {"up": "c6g.xlarge", "down": "c6g.medium", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6g.xlarge": {"up": "c6g.2xlarge", "down": "c6g.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6g.2xlarge": {"up": "c6g.4xlarge", "down": "c6g.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6g.4xlarge": {"up": "c6g.8xlarge", "down": "c6g.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6g.8xlarge": {"up": "c6g.12xlarge", "down": "c6g.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6g.12xlarge": {"up": "c6g.16xlarge", "down": "c6g.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6g.16xlarge": {"up": null, "down": "c6g.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6g.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6gd.medium": {"up": "c6gd.large", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6gd.large": {"up": "c6gd.xlarge", "down": "c6gd.medium", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6gd.xlarge": {"up": "c6gd.2xlarge", "down": "c6gd.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6gd.2xlarge": {"up": "c6gd.4xlarge", "down": "c6gd.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6gd.4xlarge": {"up": "c6gd.8xlarge", "down": "c6gd.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6gd.8xlarge": {"up": "c6gd.12xlarge", "down": "c6gd.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6gd.12xlarge": {"up": "c6gd.16xlarge", "down": "c6gd.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6gd.16xlarge": {"up": null, "down": "c6gd.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "c6gd.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "cc1.4xlarge": {"up": null, "down": null, "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "cc2.8xlarge": {"up": null, "down": null, "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "cg1.4xlarge": {"up": null, "down": null, "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "cr1.8xlarge": {"up": null, "down": null, "superseded": {"regular": "r3.8xlarge","next_gen": "r4.8xlarge", "burstable": "", "amd": ""}, "ec2_classic": true, "enhanced_networking": false},
  "d2.xlarge": {"up": "d2.2xlarge", "down": null, "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "d2.2xlarge": {"up": "d2.4xlarge", "down": "d2.xlarge", "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "d2.4xlarge": {"up": "d2.8xlarge", "down": "d2.2xlarge", "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "d2.8xlarge": {"up": null, "down": "d2.4xlarge", "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "p2.xlarge": {"up": "p2.8xlarge", "down": null, "superseded": {"regular": "p3.xlarge","next_gen": null, "burstable": "", "amd": ""}, "ec2_classic": false, "enhanced_networking": true},
  "p2.8xlarge": {"up": "p2.16xlarge", "down": "p2.xlarge", "superseded": {"regular": "p3.8xlarge","next_gen": null, "burstable": "", "amd": ""}, "ec2_classic": false, "enhanced_networking": true},
  "p2.16xlarge": {"up": null, "down": "p2.8xlarge", "superseded": {"regular": "p3.16xlarge","next_gen": null, "burstable": "", "amd": ""}, "ec2_classic": false, "enhanced_networking": true},
  "p3.2xlarge": {"up": "p3.8xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "p3.8xlarge": {"up": "p3.16xlarge", "down": "p3.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "p3.16xlarge": {"up": "p3dn.24xlarge", "down": "p3.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "p3dn.24xlarge": {"up": null, "down": "p3.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "inf1.xlarge": {"up": "inf1.2xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "inf1.2xlarge": {"up": "inf1.6xlarge", "down": "inf1.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "inf1.6xlarge": {"up": "inf1.24xlarge", "down": "inf1.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "inf1.24xlarge": {"up": null, "down": "inf1.6xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "g2.2xlarge": {"up": "g2.8xlarge", "down": null, "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "g2.8xlarge": {"up": null, "down": "g2.2xlarge", "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "g3s.xlarge": {"up": "g3.4xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "g3.4xlarge": {"up": "g3.8xlarge", "down": "g3s.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "g3.8xlarge": {"up": "g3.16xlarge", "down": "g3.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "g3.16xlarge": {"up": null, "down": "g3.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "g4.large": {"up": "g4.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "g4.2xlarge": {"up": "g4.4xlarge", "down": "g4.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "g4.4xlarge": {"up": "g4.8xlarge", "down": "g4.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "g4.8xlarge": {"up": "g4.16xlarge", "down": "g4.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "g4.16xlarge": {"up": null, "down": "g4.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "g4dn.12xlarge": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "g4dn.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "f1.2xlarge": {"up": "f1.4xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "f1.4xlarge": {"up": "f1.16xlarge", "down": "f1.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "f1.16xlarge": {"up": null, "down": "f1.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "h1.2xlarge": {"up": "h1.4xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "h1.4xlarge": {"up": "h1.8xlarge", "down": "h1.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "h1.8xlarge": {"up": "h1.16xlarge", "down": "h1.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "h1.16xlarge": {"up": null, "down": "h1.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "hi1.4xlarge": {"up": "hs1.8xlarge", "down": null, "superseded": {"regular":"i3.4xlarge", "next_gen":"", "burstable":"", "amd":""}, "ec2_classic": true, "enhanced_networking": false},
  "hs1.8xlarge": {"up": null, "down": "hi1.4xlarge", "superseded": {"regular":"d2.8xlarge", "next_gen":"", "burstable":"", "amd":""}, "ec2_classic": true, "enhanced_networking": false},
  "i2.xlarge": {"up": "i2.2xlarge", "down": null, "superseded": {"regular":"i3.xlarge", "next_gen":"", "burstable":"", "amd":""}, "ec2_classic": true, "enhanced_networking": false},
  "i2.2xlarge": {"up": "i2.4xlarge", "down": "i2.xlarge", "superseded": {"regular":"i3.2xlarge", "next_gen":"", "burstable":"", "amd":""}, "ec2_classic": true, "enhanced_networking": false},
  "i2.4xlarge": {"up": "i2.8xlarge", "down": "i2.2xlarge", "superseded":{"regular":"i3.4xlarge", "next_gen":"", "burstable":"", "amd":""}, "ec2_classic": true, "enhanced_networking": false},
  "i2.8xlarge": {"up": null, "down": "i2.4xlarge", "superseded": {"regular":"i3.8xlarge", "next_gen":"", "burstable":"", "amd":""}, "ec2_classic": true, "enhanced_networking": false},
  "i3.large": {"up": "i3.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3.xlarge": {"up": "i3.2xlarge", "down": "i3.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3.2xlarge": {"up": "i3.4xlarge", "down": "i3.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3.4xlarge": {"up": "i3.8xlarge", "down": "i3.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3.8xlarge": {"up": "i3.16xlarge", "down": "i3.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3.16xlarge": {"up": null, "down": "i3.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3en.large": {"up": "i3en.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3en.xlarge": {"up": "i3en.2xlarge", "down": "i3en.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3en.2xlarge": {"up": "i3en.3xlarge", "down": "i3en.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3en.3xlarge": {"up": "i3en.6xlarge", "down": "i3en.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3en.6xlarge": {"up": "i3en.12xlarge", "down": "i3en.3xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3en.12xlarge": {"up": "i3en.24xlarge", "down": "i3en.6xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3en.24xlarge": {"up": null, "down": "i3en.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "i3en.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m1.small": {"up": "m1.medium", "down": null, "superseded": {"regular":"t3.large", "next_gen":"", "burstable":"t3.large", "amd":"m5a.large"}, "ec2_classic": true, "enhanced_networking": false},
  "m1.medium": {"up": "m1.large", "down": "m1.small", "superseded": {"regular":"m5.large", "next_gen":"", "burstable":"t3.large", "amd":"m5a.large"}, "ec2_classic": true, "enhanced_networking": false},
  "m1.large": {"up": "m1.xlarge", "down": "m1.medium", "superseded": {"regular":"m5.large", "next_gen":"", "burstable":"t3.xlarge", "amd":"m5a.large"}, "ec2_classic": true, "enhanced_networking": false},
  "m1.xlarge": {"up": null, "down": "m1.large" , "superseded": {"regular":"m5.xlarge", "next_gen":"", "burstable":"t3.2xlarge", "amd":"m5a.xlarge"}, "ec2_classic": true, "enhanced_networking": false},
  "m2.xlarge": {"up": "m2.2xlarge", "down": null, "superseded": {"regular":"r3.large", "next_gen":"r5.large", "burstable":"", "amd":"r5a.large"}, "ec2_classic": true, "enhanced_networking": false},
  "m2.2xlarge": {"up": "m2.4xlarge", "down": "m2.xlarge", "superseded": {"regular":"r3.xlarge", "next_gen":"r5.xlarge", "burstable":"", "amd":"r5a.xlarge"}, "ec2_classic": true, "enhanced_networking": false},
  "m2.4xlarge": {"up": null, "down": "m2.2xlarge", "superseded": {"regular":"r3.2xlarge", "next_gen":"r5.2xlarge", "burstable":"", "amd":"r5a.2xlarge"}, "ec2_classic": true, "enhanced_networking": false},
  "m3.medium": {"up": "m3.large", "down": null, "superseded": {"regular":"m5.large", "next_gen":"", "burstable":"t3.large", "amd":"m5a.large"}, "ec2_classic": true, "enhanced_networking": false},
  "m3.large": {"up": "m3.xlarge", "down": "m3.medium", "superseded": {"regular":"m5.large", "next_gen":"", "burstable":"t3.xlarge", "amd":"m5a.large"}, "ec2_classic": true, "enhanced_networking": false},
  "m3.xlarge": {"up": "m3.2xlarge", "down": "m3.large", "superseded": {"regular":"m5.xlarge", "next_gen":"", "burstable":"t3.2xlarge", "amd":"m5a.xlarge"}, "ec2_classic": true, "enhanced_networking": false},
  "m3.2xlarge": {"up": null, "down": "m3.xlarge", "superseded": {"regular":"m5.2xlarge", "next_gen":"", "burstable":"", "amd":"m5a.2xlarge"}, "ec2_classic": true, "enhanced_networking": false},
  "m4.large": {"up": "m4.xlarge", "down": null, "superseded": {"regular":"m5.large", "next_gen":"", "burstable":"t3.xlarge", "amd":"m5a.large"}, "ec2_classic": false, "enhanced_networking": false},
  "m4.xlarge": {"up": "m4.2xlarge", "down": "m4.large", "superseded": {"regular":"m5.xlarge", "next_gen":"", "burstable":"t3.2xlarge", "amd":"m5a.xlarge"}, "ec2_classic": false, "enhanced_networking": false},
  "m4.2xlarge": {"up": "m4.4xlarge", "down": "m4.xlarge", "superseded": {"regular":"m5.2xlarge", "next_gen":"", "burstable":"", "amd":"m5a.2xlarge"}, "ec2_classic": false, "enhanced_networking": false},
  "m4.4xlarge": {"up": "m4.10xlarge", "down": "m4.2xlarge", "superseded": {"regular":"m5.4xlarge", "next_gen":"", "burstable":"", "amd":"m5a.4xlarge"}, "ec2_classic": false, "enhanced_networking": false},
  "m4.10xlarge": {"up": "m4.16xlarge", "down": "m4.4xlarge", "superseded": {"regular":"m5.12xlarge", "next_gen":"", "burstable":"", "amd":"m5a.12xlarge"}, "ec2_classic": false, "enhanced_networking": false},
  "m4.16xlarge": {"up": null, "down": "m4.10xlarge", "superseded": {"regular":"m5.16xlarge", "next_gen":"", "burstable":"", "amd":"m5a.16xlarge"}, "ec2_classic": false, "enhanced_networking": true},
  "m5.large": {"up": "m5.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5.xlarge": {"up": "m5.2xlarge", "down": "m5.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5.2xlarge": {"up": "m5.4xlarge", "down": "m5.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5.4xlarge": {"up": "m5.8xlarge", "down": "m5.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5.8xlarge": {"up": "m5.12xlarge", "down": "m5.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5.12xlarge": {"up": "m5.24xlarge", "down": "m5.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5.24xlarge": {"up": null, "down": "m5.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5n.large": {"up": "m5n.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5n.xlarge": {"up": "m5n.2xlarge", "down": "m5n.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5n.2xlarge": {"up": "m5n.4xlarge", "down": "m5n.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5n.4xlarge": {"up": "m5n.8xlarge", "down": "m5n.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5n.8xlarge": {"up": "m5n.12xlarge", "down": "m5n.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5n.12xlarge": {"up": "m5n.16xlarge", "down": "m5n.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5n.16xlarge": {"up": "m5n.24xlarge", "down": "m5n.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5n.24xlarge": {"up": null, "down": "m5n.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5dn.large": {"up": "m5dn.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5dn.xlarge": {"up": "m5dn.2xlarge", "down": "m5dn.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5dn.2xlarge": {"up": "m5dn.4xlarge", "down": "m5dn.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5dn.4xlarge": {"up": "m5dn.8xlarge", "down": "m5dn.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5dn.8xlarge": {"up": "m5dn.12xlarge", "down": "m5dn.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5dn.12xlarge": {"up": "m5dn.16xlarge", "down": "m5dn.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5dn.16xlarge": {"up": "m5dn.24xlarge", "down": "m5dn.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5dn.24xlarge": {"up": null, "down": "m5dn.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6g.medium": {"up": "m6g.large", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6g.large": {"up": "m6g.xlarge", "down": "m6g.medium", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6g.xlarge": {"up": "m6g.2xlarge", "down": "m6g.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6g.2xlarge": {"up": "m6g.4xlarge", "down": "m6g.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6g.4xlarge": {"up": "m6g.8xlarge", "down": "m6g.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6g.8xlarge": {"up": "m6g.12xlarge", "down": "m6g.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6g.12xlarge": {"up": "m6g.16xlarge", "down": "m6g.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6g.16xlarge": {"up": "m6g.24xlarge", "down": "m6g.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6g.24xlarge": {"up": null, "down": "m6g.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6g.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6gd.medium": {"up": "m6gd.large", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6gd.large": {"up": "m6gd.xlarge", "down": "m6gd.medium", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6gd.xlarge": {"up": "m6gd.2xlarge", "down": "m6gd.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6gd.2xlarge": {"up": "m6gd.4xlarge", "down": "m6gd.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6gd.4xlarge": {"up": "m6gd.8xlarge", "down": "m6gd.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6gd.8xlarge": {"up": "m6gd.12xlarge", "down": "m6gd.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6gd.12xlarge": {"up": "m6gd.16xlarge", "down": "m6gd.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6gd.16xlarge": {"up": "m6gd.24xlarge", "down": "m6gd.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6gd.24xlarge": {"up": null, "down": "m6gd.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m6gd.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5a.large": {"up": "m5a.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5a.xlarge": {"up": "m5a.2xlarge", "down": "m5a.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5a.2xlarge": {"up": "m5a.4xlarge", "down": "m5a.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5a.4xlarge": {"up": "m5a.8xlarge", "down": "m5a.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5a.8xlarge": {"up": "m5a.12xlarge", "down": "m5a.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5a.12xlarge": {"up": "m5a.16xlarge", "down": "m5a.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5a.16xlarge": {"up": "m5a.24xlarge", "down": "m5a.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5a.24xlarge": {"up": null, "down": "m5a.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5ad.large": {"up": "m5ad.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5ad.xlarge": {"up": "m5ad.2xlarge", "down": "m5ad.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5ad.2xlarge": {"up": "m5ad.4xlarge", "down": "m5ad.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5ad.4xlarge": {"up": "m5ad.8xlarge", "down": "m5ad.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5ad.8xlarge": {"up": "m5ad.12xlarge", "down": "m5ad.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5ad.12xlarge": {"up": "m5ad.16xlarge", "down": "m5ad.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5ad.16xlarge": {"up": "m5ad.24xlarge", "down": "m5ad.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5ad.24xlarge": {"up": null, "down": "m5ad.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5d.large": {"up": "m5d.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5d.xlarge": {"up": "m5d.2xlarge", "down": "m5d.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5d.2xlarge": {"up": "m5d.4xlarge", "down": "m5d.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5d.4xlarge": {"up": "m5d.8xlarge", "down": "m5d.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5d.8xlarge": {"up": "m5d.12xlarge", "down": "m5d.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5d.12xlarge": {"up": "m5d.16xlarge", "down": "m5d.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5d.16xlarge": {"up": "m5d.24xlarge", "down": "m5d.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5d.24xlarge": {"up": null, "down": "m5d.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "m5d.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r3.large": {"up": "r3.xlarge", "down": null, "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "r3.xlarge": {"up": "r3.2xlarge", "down": "r3.large", "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "r3.2xlarge": {"up": "r3.4xlarge", "down": "r3.xlarge", "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "r3.4xlarge": {"up": "r3.8xlarge", "down": "r3.2xlarge", "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "r3.8xlarge": {"up": null, "down": "r3.4xlarge", "superseded": null, "ec2_classic": true, "enhanced_networking": false},
  "r4.large": {"up": "r4.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r4.xlarge": {"up": "r4.2xlarge", "down": "r4.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r4.2xlarge": {"up": "r4.4xlarge", "down": "r4.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r4.4xlarge": {"up": "r4.8xlarge", "down": "r4.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r4.8xlarge": {"up": "r4.16xlarge", "down": "r4.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r4.16xlarge": {"up": null, "down": "r4.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5.large": {"up": "r5.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5.xlarge": {"up": "r5.2xlarge", "down": "r5.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5.2xlarge": {"up": "r5.4xlarge", "down": "r5.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5.4xlarge": {"up": "r5.8xlarge", "down": "r5.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5.8xlarge": {"up": "r5.12xlarge", "down": "r5.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5.12xlarge": {"up": "r5.16xlarge", "down": "r5.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5.16xlarge": {"up": "r5.24xlarge", "down": "r5.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5.24xlarge": {"up": null, "down": "r5.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5a.large": {"up": "r5a.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5a.xlarge": {"up": "r5a.2xlarge", "down": "r5a.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5a.2xlarge": {"up": "r5a.4xlarge", "down": "r5a.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5a.4xlarge": {"up": "r5a.8xlarge", "down": "r5a.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5a.8xlarge": {"up": "r5a.12xlarge", "down": "r5a.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5a.12xlarge": {"up": "r5a.16xlarge", "down": "r5a.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5a.16xlarge": {"up": "r5a.24xlarge", "down": "r5a.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5a.24xlarge": {"up": null, "down": "r5a.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5ad.large": {"up": "r5ad.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5ad.xlarge": {"up": "r5ad.2xlarge", "down": "r5ad.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5ad.2xlarge": {"up": "r5ad.4xlarge", "down": "r5ad.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5ad.4xlarge": {"up": "r5ad.8xlarge", "down": "r5ad.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5ad.8xlarge": {"up": "r5ad.12xlarge", "down": "r5ad.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5ad.12xlarge": {"up": "r5ad.16xlarge", "down": "r5ad.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5ad.16xlarge": {"up": "r5ad.24xlarge", "down": "r5ad.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5ad.24xlarge": {"up": null, "down": "r5ad.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5n.large": {"up": "r5n.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5n.xlarge": {"up": "r5n.2xlarge", "down": "r5n.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5n.2xlarge": {"up": "r5n.4xlarge", "down": "r5n.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5n.4xlarge": {"up": "r5n.8xlarge", "down": "r5n.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5n.8xlarge": {"up": "r5n.12xlarge", "down": "r5n.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5n.12xlarge": {"up": "r5n.16xlarge", "down": "r5n.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5n.16xlarge": {"up": "r5n.24xlarge", "down": "r5n.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5n.24xlarge": {"up": null, "down": "r5n.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5dn.large": {"up": "r5dn.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5dn.xlarge": {"up": "r5dn.2xlarge", "down": "r5dn.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5dn.2xlarge": {"up": "r5dn.4xlarge", "down": "r5dn.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5dn.4xlarge": {"up": "r5dn.8xlarge", "down": "r5dn.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5dn.8xlarge": {"up": "r5dn.12xlarge", "down": "r5dn.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5dn.12xlarge": {"up": "r5dn.16xlarge", "down": "r5dn.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5dn.16xlarge": {"up": "r5dn.24xlarge", "down": "r5dn.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5dn.24xlarge": {"up": null, "down": "r5dn.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5d.large": {"up": "r5d.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5d.xlarge": {"up": "r5d.2xlarge", "down": "r5d.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5d.2xlarge": {"up": "r5d.4xlarge", "down": "r5d.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5d.4xlarge": {"up": "r5d.8xlarge", "down": "r5d.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5d.8xlarge": {"up": "r5d.12xlarge", "down": "r5d.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5d.12xlarge": {"up": "r5d.16xlarge", "down": "r5d.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5d.16xlarge": {"up": "r5d.24xlarge", "down": "r5d.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5d.24xlarge": {"up": null, "down": "r5d.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r5d.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6g.medium": {"up": "r6g.large", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6g.large": {"up": "r6g.xlarge", "down": "r6g.medium", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6g.xlarge": {"up": "r6g.2xlarge", "down": "r6g.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6g.2xlarge": {"up": "r6g.4xlarge", "down": "r6g.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6g.4xlarge": {"up": "r6g.8xlarge", "down": "r6g.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6g.8xlarge": {"up": "r6g.12xlarge", "down": "r6g.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6g.12xlarge": {"up": "r6g.16xlarge", "down": "r6g.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6g.16xlarge": {"up": null, "down": "r6g.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6g.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6gd.medium": {"up": "r6gd.large", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6gd.large": {"up": "r6gd.xlarge", "down": "r6gd.medium", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6gd.xlarge": {"up": "r6gd.2xlarge", "down": "r6gd.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6gd.2xlarge": {"up": "r6gd.4xlarge", "down": "r6gd.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6gd.4xlarge": {"up": "r6gd.8xlarge", "down": "r6gd.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6gd.8xlarge": {"up": "r6gd.12xlarge", "down": "r6gd.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6gd.12xlarge": {"up": "r6gd.16xlarge", "down": "r6gd.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6gd.16xlarge": {"up": null, "down": "r6gd.12xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "r6gd.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "x1.16xlarge": {"up": "x1.32xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "x1.32xlarge": {"up": null, "down": "x1.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "x1e.xlarge": {"up": "x1e.2xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "x1e.2xlarge": {"up": "x1e.4xlarge", "down": "x1e.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "x1e.4xlarge": {"up": "x1e.8xlarge", "down": "x1e.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "x1e.8xlarge": {"up": "x1e.16xlarge", "down": "x1e.4xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "x1e.16xlarge": {"up": "x1e.32xlarge", "down": "x1e.8xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "x1e.32xlarge": {"up": null, "down": "x1e.16xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "z1d.large": {"up": "z1d.xlarge", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "z1d.xlarge": {"up": "z1d.2xlarge", "down": "z1d.large", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "z1d.2xlarge": {"up": "z1d.3xlarge", "down": "z1d.xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "z1d.3xlarge": {"up": "z1d.6xlarge", "down": "z1d.2xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "z1d.6xlarge": {"up": "z1d.12xlarge", "down": "z1d.3xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "z1d.12xlarge": {"up": null, "down": "z1d.6xlarge", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "z1d.metal": {"up": null, "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "u-6tb1.metal": {"up": "u-9tb1.metal", "down": null, "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "u-9tb1.metal": {"up": "u-12tb1.metal", "down": "u-6tb1.metal", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "u-12tb1.metal": {"up": "u-18tb1.metal", "down": "u-9tb1.metal", "superseded": null, "ec2_classic": false, "enhanced_networking": true},
  "u-18tb1.metal": {"up": "u-24tb1.metal", "down": "u-12tb1.metal", "superseded": null, "ec2_classic": false, "enhanced_networking": true}
}